class Caber::InstallGenerator < Rails::Generators::Base
  def create_initializer_file
    create_file "config/initializers/caber.rb", <<~EOF
      # Autogenerated configuration for Caber
      Caber.configure do |config|

        # List the object-level permissions you want
        config.permissions = [
          :view,
          :edit,
          :own
        ]
      end
    EOF
  end
end
