name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run tests
        uses: paambaati/codeclimate-action@v9.0.0
        with:
          coverageCommand: bundle exec rake spec
        env:
          CC_TEST_REPORTER_ID: 5dd5918c241368d9507f58b71461de2d22d4f18ca23aadb23dc7ff2d707dabf6
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint Ruby code
        run: bundle exec standardrb
